// Copyright (c) 2025 Ekkodale GmbH. All rights reserved.
//
// This file is part of the gaeco platform system.
//
// Use of this file is governed by the terms of the license
// in LICENSE.md at the root of this repository.
// Unauthorized copying, modification, distribution, or use of this file,
// via any medium, is strictly prohibited except as expressly permitted
// under that license.

using FastEndpoints;
using NSubstitute;
using PluginHost.Api.Endpoints.Plugins;
using PluginHost.Domain.Repositories;

namespace PluginHost.Api.Tests.Endpoints.Plugins;

public class GetAllPluginsEndpointTests
{
    private readonly IPluginRepository _pluginRepository;
    private readonly GetAllPlugins _endpoint;

    public GetAllPluginsEndpointTests()
    {
        _pluginRepository = Substitute.For<IPluginRepository>();
        var mapper = PluginEndpointTestHelper.CreateMapper();
        _endpoint = Factory.Create<GetAllPlugins>(_pluginRepository, mapper);
    }

    [Fact]
    public async Task HandleAsync_ReturnsOkWithDtosForEachPlugin()
    {
        // Arrange
        _pluginRepository.GetAllPlugins().Returns(
        [
            PluginTestData.Create("plugin-a", "Plugin A"),
            PluginTestData.Create("plugin-b", "Plugin B")
        ]);

        // Act
        await _endpoint.HandleAsync(default);

        // Assert – both plugins are present with correct IDs and names
        Assert.Equal(200, _endpoint.HttpContext.Response.StatusCode);
        var result = _endpoint.Response.ToList();
        Assert.Equal(2, result.Count);
        Assert.Contains(result, d => d.Id == "plugin-a" && d.Name == "Plugin A");
        Assert.Contains(result, d => d.Id == "plugin-b" && d.Name == "Plugin B");
    }

    [Fact]
    public async Task HandleAsync_ReturnsOkWithEmptyList_WhenNoPluginsRegistered()
    {
        // Arrange
        _pluginRepository.GetAllPlugins().Returns([]);

        // Act
        await _endpoint.HandleAsync(default);

        // Assert
        Assert.Equal(200, _endpoint.HttpContext.Response.StatusCode);
        Assert.Empty(_endpoint.Response);
    }

    [Fact]
    public async Task HandleAsync_OmitsRemoteEntryUrl_ForEachPlugin()
    {
        // Arrange – the admin list endpoint must not expose the raw remote-entry URL
        _pluginRepository.GetAllPlugins().Returns([PluginTestData.Create("plugin-a")]);

        // Act
        await _endpoint.HandleAsync(default);

        // Assert – Url is intentionally empty; IconUrl must still be present
        var dto = _endpoint.Response.First();
        Assert.Equal(string.Empty, dto.Url);
        Assert.NotEmpty(dto.IconUrl);
    }

    [Fact]
    public async Task HandleAsync_IncludesSignedIconUrl_ForEachPlugin()
    {
        // Arrange
        _pluginRepository.GetAllPlugins().Returns([PluginTestData.Create("plugin-a")]);

        // Act
        await _endpoint.HandleAsync(default);

        // Assert – icon URL is generated by the mapper and must be an absolute URL
        var iconUrl = _endpoint.Response.First().IconUrl;
        Assert.NotEmpty(iconUrl);
        Assert.True(iconUrl.StartsWith("http://") || iconUrl.StartsWith("https://"),
            $"Expected an absolute URL but got: {iconUrl}");
    }
}
