// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PluginHost.Infrastructure;

#nullable disable

namespace PluginHost.Infrastructure.Migrations
{
    [DbContext(typeof(PluginHostDbContext))]
    [Migration("20260318223040_newname")]
    partial class newname
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PluginHost.Domain.Models.Plugin", b =>
                {
                    b.Property<string>("PluginId")
                        .HasColumnType("text");

                    b.Property<string>("ContainerUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntryPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PluginId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Route")
                        .IsUnique();

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("PluginHost.Domain.Models.PluginGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("GroupId");

                    b.ToTable("PluginGroups");
                });

            modelBuilder.Entity("PluginHost.Domain.Models.Plugin", b =>
                {
                    b.HasOne("PluginHost.Domain.Models.PluginGroup", "Group")
                        .WithMany("Plugins")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PluginHost.Domain.Models.PluginGroup", b =>
                {
                    b.Navigation("Plugins");
                });
#pragma warning restore 612, 618
        }
    }
}
